apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: pythoncontainer
    image: my-python-image
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: python-port
    protocol: TCP
  selector:
    app: python
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: Pythonreplicas
  labels:
    app: python
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: pythonreplicacontainer
        image: my-python-image
        ports:
        - name: nodejs-port
          containerPort: 3000
