---
apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: pythoncontainer
    image: my-python-image
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: python-port
    protocol: TCP
  selector:
    app: python
  type: NodePort
---
